"""add_geog_column

Revision ID: 34fec6103cd7
Revises: 9234380ecd41
Create Date: 2026-01-16 12:19:32.336074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '34fec6103cd7'
down_revision: Union[str, None] = '9234380ecd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    #op.create_index('idx_restaurants_geog', 'restaurants', ['geog'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_restaurants_geog', table_name='restaurants', postgresql_using='gist')
    op.drop_column('restaurants', 'geog')
    # ### end Alembic commands ###