"""Adicionado campo offer image url

Revision ID: 410ea5984023
Revises: f26c955c11a3
Create Date: 2026-01-27 09:44:00.440060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410ea5984023'
down_revision: Union[str, None] = 'f26c955c11a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer_targets', 'target_distance',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('offer_targets', 'placement',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'NORMAL'::text"))
    op.drop_index(op.f('idx_offer_targets_cli_geog'), table_name='offer_targets', postgresql_using='gist')
    op.drop_index(op.f('idx_offer_targets_res_geog'), table_name='offer_targets', postgresql_using='gist')
    op.create_index('idx_offer_targets_geog_cli', 'offer_targets', ['geog_cli'], unique=False, postgresql_using='gist')
    op.create_index('idx_offer_targets_geog_res', 'offer_targets', ['geog_res'], unique=False, postgresql_using='gist')
    op.add_column('offers', sa.Column('offer_image_urls', sa.String(), nullable=True))
    op.drop_constraint(op.f('restaurant_reviews_offer_claim_id_fkey'), 'restaurant_reviews', type_='foreignkey')
    op.drop_constraint(op.f('restaurant_reviews_client_id_fkey'), 'restaurant_reviews', type_='foreignkey')
    op.drop_constraint(op.f('restaurant_reviews_restaurant_id_fkey'), 'restaurant_reviews', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('restaurant_reviews_restaurant_id_fkey'), 'restaurant_reviews', 'restaurants', ['restaurant_id'], ['id'])
    op.create_foreign_key(op.f('restaurant_reviews_client_id_fkey'), 'restaurant_reviews', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('restaurant_reviews_offer_claim_id_fkey'), 'restaurant_reviews', 'offer_claims', ['offer_claim_id'], ['id'])
    op.drop_column('offers', 'offer_image_urls')
    op.drop_index('idx_offer_targets_geog_res', table_name='offer_targets', postgresql_using='gist')
    op.drop_index('idx_offer_targets_geog_cli', table_name='offer_targets', postgresql_using='gist')
    op.create_index(op.f('idx_offer_targets_res_geog'), 'offer_targets', ['geog_res'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_offer_targets_cli_geog'), 'offer_targets', ['geog_cli'], unique=False, postgresql_using='gist')
    op.alter_column('offer_targets', 'placement',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'NORMAL'::text"))
    op.alter_column('offer_targets', 'target_distance',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###