"""Adicionado Stats

Revision ID: 51f025904eff
Revises: f407e823214c
Create Date: 2026-01-29 16:25:46.883067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f025904eff'
down_revision: Union[str, None] = 'f407e823214c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'offer_targets', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     op.drop_constraint(None, 'offer_targets', type_='foreignkey')
    # ### end Alembic commands ###