"""add_geog_column_client

Revision ID: 75f585ef5cef
Revises: 34fec6103cd7
Create Date: 2026-01-16 13:02:57.964118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '75f585ef5cef'
down_revision: Union[str, None] = '34fec6103cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    # op.create_index('idx_clients_geog', 'clients', ['geog'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_clients_geog', table_name='clients', postgresql_using='gist')
    op.drop_column('clients', 'geog')
    # ### end Alembic commands ###