"""add_km_wallet

Revision ID: 7c4529ffcfd7
Revises: c414d9c31623
Create Date: 2026-01-16 22:06:42.865983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4529ffcfd7'
down_revision: Union[str, None] = 'c414d9c31623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('cost_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('restaurants', sa.Column('balance_km', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'balance_km')
    op.drop_column('offers', 'cost_amount')
    op.drop_column('offers', 'payment_method')
    # ### end Alembic commands ###