"""initial_structure_v1

Revision ID: 9234380ecd41
Revises: 
Create Date: 2026-01-16 10:52:46.451460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9234380ecd41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone_e164', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('last_loc_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loc_accuracy_m', sa.Integer(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_e164')
    )
    op.create_table('client_stats',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('redeemed_count', sa.Integer(), nullable=False),
    sa.Column('no_show_count', sa.Integer(), nullable=False),
    sa.Column('last_no_show_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('offer_claims',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('qr_token', sa.UUID(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('penalty_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACCEPTED','REDEEMED','CANCELLED','NO_SHOW')", name='ck_offer_claim_status'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', 'client_id', name='uq_offer_client')
    )
    op.create_table('offer_targets',
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_no', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_targets')
    op.drop_table('offer_claims')
    op.drop_table('client_stats')
    op.drop_table('clients')
    # ### end Alembic commands ###