"""add new architeture of restaurantes features

Revision ID: bc80e6507e06
Revises: ccae081b9272
Create Date: 2026-01-20 11:13:33.789966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc80e6507e06'
down_revision: Union[str, None] = 'ccae081b9272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_groups',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('max_select', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('features',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.SmallInteger(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['feature_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'slug', name='uq_feature_group_slug')
    )
   # op.drop_table('cuisine_types', cascade='all, delete')
    op.drop_table('restaurant_cuisine_features')
    op.drop_table('restaurant_space_features')
   # op.drop_table('space_features', cascade='all, delete')
    op.drop_table('restaurant_cuisine_types')
   # op.drop_table('cuisine_features', cascade='all, delete')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisine_features',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cuisine_features_pkey')),
    sa.UniqueConstraint('slug', name=op.f('cuisine_features_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('restaurant_cuisine_types',
    sa.Column('restaurant_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('cuisine_type_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cuisine_type_id'], ['cuisine_types.id'], name=op.f('restaurant_cuisine_types_cuisine_type_id_fkey')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('restaurant_cuisine_types_restaurant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('restaurant_id', 'cuisine_type_id', name=op.f('restaurant_cuisine_types_pkey'))
    )
    op.create_table('space_features',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('space_features_pkey')),
    sa.UniqueConstraint('slug', name=op.f('space_features_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('restaurant_space_features',
    sa.Column('restaurant_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('feature_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['space_features.id'], name=op.f('restaurant_space_features_feature_id_fkey')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('restaurant_space_features_restaurant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('restaurant_id', 'feature_id', name=op.f('restaurant_space_features_pkey'))
    )
    op.create_table('restaurant_cuisine_features',
    sa.Column('restaurant_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('feature_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['cuisine_features.id'], name=op.f('restaurant_cuisine_features_feature_id_fkey')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('restaurant_cuisine_features_restaurant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('restaurant_id', 'feature_id', name=op.f('restaurant_cuisine_features_pkey'))
    )
    op.create_table('cuisine_types',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cuisine_types_pkey')),
    sa.UniqueConstraint('slug', name=op.f('cuisine_types_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('features')
    op.drop_table('feature_groups')
    # ### end Alembic commands ###