"""add client_first_access

Revision ID: c3ad7ebfd5d4
Revises: bc8ca5dea2c2
Create Date: 2026-01-21 15:37:39.573070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3ad7ebfd5d4'
down_revision: Union[str, None] = 'bc8ca5dea2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_first_access',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), server_default='PENDING', nullable=False),
    sa.Column('code', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('phone_e164', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('restaurant_features', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_restaurant_features_feature'), table_name='restaurant_features')
    op.alter_column('restaurants', 'working_hours',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_column('restaurants', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('restaurants', 'working_hours',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_index(op.f('idx_restaurant_features_feature'), 'restaurant_features', ['feature_id'], unique=False)
    op.alter_column('restaurant_features', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table('client_first_access')
    # ### end Alembic commands ###