"""Recriando migration perdida

Revision ID: f26c955c11a3
Revises: c3ad7ebfd5d4
Create Date: 2026-01-27 08:22:33.265967

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f26c955c11a3'
down_revision: Union[str, None] = 'c3ad7ebfd5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_offer_targets_cli_geog', 'offer_targets', ['geog_cli'], unique=False, postgresql_using='gist')
    op.create_index('idx_offer_targets_res_geog', 'offer_targets', ['geog_res'], unique=False, postgresql_using='gist')
    op.create_index('idx_offers_geog', 'offers', ['geog'], unique=False, postgresql_using='gist')
    op.alter_column('restaurant_reviews', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('restaurant_reviews', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('restaurant_reviews', 'restaurant_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('restaurant_reviews', 'offer_claim_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('restaurant_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'restaurant_reviews', ['offer_claim_id'])
    op.create_foreign_key(None, 'restaurant_reviews', 'offer_claims', ['offer_claim_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'restaurant_reviews', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'restaurant_reviews', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant_reviews', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_reviews', type_='unique')
    op.alter_column('restaurant_reviews', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('restaurant_reviews', 'offer_claim_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('restaurant_reviews', 'restaurant_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('restaurant_reviews', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('restaurant_reviews', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_offer_targets_cli_geog', table_name='offer_targets', postgresql_using='gist')
    op.alter_column('offer_targets', 'target_distance',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###