"""Adicionados Account and Favourites

Revision ID: f3d9c36223ff
Revises: 410ea5984023
Create Date: 2026-01-28 16:37:16.812870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d9c36223ff'
down_revision: Union[str, None] = '410ea5984023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_select', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favourites_group_code'), 'favourites_group', ['code'], unique=True)
    op.create_index(op.f('ix_favourites_group_id'), 'favourites_group', ['id'], unique=False)
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['favourites_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favourites_id'), 'favourites', ['id'], unique=False)
    op.create_index(op.f('ix_favourites_slug'), 'favourites', ['slug'], unique=True)
    op.create_table('restaurant_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('balance_km', sa.Float(), nullable=False),
    sa.Column('package_id', sa.String(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('date_of_bte', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_account_id'), 'restaurant_account', ['id'], unique=False)
    op.create_table('client_favourites',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('favourite_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['favourite_id'], ['favourites.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'favourite_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_favourites')
    op.drop_index(op.f('ix_restaurant_account_id'), table_name='restaurant_account')
    op.drop_table('restaurant_account')
    op.drop_index(op.f('ix_favourites_slug'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_id'), table_name='favourites')
    op.drop_table('favourites')
    op.drop_index(op.f('ix_favourites_group_id'), table_name='favourites_group')
    op.drop_index(op.f('ix_favourites_group_code'), table_name='favourites_group')
    op.drop_table('favourites_group')
    # ### end Alembic commands ###